<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <!-- This Imports Il2CppInterop.Common + The stuff in btd6.targets -->
    <Import Project="..\btd6.targets" />
    <ItemGroup>
        <Reference Include="$(ManagedFolder)\Il2CppInterop.Common.dll" Private="false"/>
    </ItemGroup>
</Project>
