<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <RootNamespace>BTD6Rogue</RootNamespace>
        <Configurations>Debug;Release</Configurations>
        <Nullable>enable</Nullable>
        <AssemblyName>BTD6Rogue</AssemblyName>
        <LangVersion>latest</LangVersion>
        <Optimize>False</Optimize>
        <DebugType>embedded</DebugType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <ItemGroup>
      <Compile Remove=".github\**" />
      <Compile Remove="Artifact\**" />
      <Compile Remove="bin\**" />
      <Compile Remove="Interface\Screen\**" />
      <Compile Remove="obj\**" />
      <Compile Remove="Portal\**" />
      <EmbeddedResource Remove=".github\**" />
      <EmbeddedResource Remove="Artifact\**" />
      <EmbeddedResource Remove="bin\**" />
      <EmbeddedResource Remove="Interface\Screen\**" />
      <EmbeddedResource Remove="obj\**" />
      <EmbeddedResource Remove="Portal\**" />
      <None Remove=".github\**" />
      <None Remove="Artifact\**" />
      <None Remove="bin\**" />
      <None Remove="Interface\Screen\**" />
      <None Remove="obj\**" />
      <None Remove="Portal\**" />
    </ItemGroup>

	<Import Project="..\btd6.targets" />

    <ItemGroup>
      <Compile Remove="Gamemode\Gamemodes\BlitzMode.cs" />
      <Compile Remove="Interface\Panels\ArtifactChoicePanel.cs" />
      <Compile Remove="Interface\Panels\InitialHeroChoicePanel.cs" />
      <Compile Remove="Modifier\Modifiers\OForceFortifiedModifier.cs" />
      <Compile Remove="Modifier\Modifiers\OForceLeadModifier.cs" />
      <Compile Remove="Modifier\Modifiers\OPrismaticShard.cs" />
      <Compile Remove="Patch\HeroAddXpPatch.cs" />
      <Compile Remove="Patch\InGame\OnMatchStartPatch.cs" />
      <Compile Remove="Patch\InGame\OnRestartPatch.cs" />
      <Compile Remove="Patch\InGame\OnRoundStartPatch.cs" />
      <Compile Remove="Patch\IsUpgradePathClosedPatch.cs" />
      <Compile Remove="Patch\ModeScreenOpenPatch.cs" />
      <Compile Remove="Patch\OnCashAddedPatch.cs" />
      <Compile Remove="Patch\OnMatchStartPatch.cs" />
      <Compile Remove="Patch\OnRestartPatch.cs" />
      <Compile Remove="Patch\OnRoundStartPatch.cs" />
      <Compile Remove="Patch\OnTowerCreatedPatch.cs" />
      <Compile Remove="Patch\OnUpdatePatch.cs" />
      <Compile Remove="Round\RoundConfig.cs" />
      <Compile Remove="Round\RoundGenerator.cs" />
      <Compile Remove="Towers\Modded\CyberMonkey.cs" />
      <Compile Remove="Towers\Modded\Powers\CamoTrap.cs" />
      <Compile Remove="Towers\Modded\Powers\CaveMonkey.cs" />
      <Compile Remove="Towers\Modded\Powers\GlueTrap.cs" />
      <Compile Remove="Towers\Modded\Powers\MonkeyBoost.cs" />
      <Compile Remove="Towers\Modded\Powers\RoadSpikes.cs" />
      <Compile Remove="Towers\Paragons\ModdedParagons\CaveMonkeyParagon.cs" />
      <Compile Remove="Towers\Paragons\ModdedParagons\CyberMonkey.cs" />
      <Compile Remove="Towers\Paragons\ModdedParagons\MonkeyOfLight.cs" />
      <Compile Remove="Towers\Paragons\ModdedParagons\PlasmaMonkey.cs" />
      <Compile Remove="Towers\TowerConfig.cs" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Event\" />
      <Folder Include="Data\" />
      <Folder Include="Interface\Overlay\" />
      <Folder Include="Resources\Data\" />
    </ItemGroup>

    <ItemGroup>
      <None Include="BTD6Rogue.sln" />
      <None Include="Modifier\Modifiers\OForceFortifiedModifier.cs" />
      <None Include="Modifier\Modifiers\OForceLeadModifier.cs" />
      <None Include="Modifier\Modifiers\OPrismaticShard.cs" />
      <EmbeddedResource Include="Towers\Modded\CyberMonkey.cs" />
      <None Include="Towers\Modded\Powers\CamoTrap.cs" />
      <None Include="Towers\Modded\Powers\CaveMonkey.cs" />
      <None Include="Towers\Modded\Powers\GlueTrap.cs" />
      <None Include="Towers\Modded\Powers\MonkeyBoost.cs" />
      <None Include="Towers\Modded\Powers\RoadSpikes.cs" />
      <None Include="Towers\Modded\TempleBase.cs" />
      <None Include="Towers\Paragons\ModdedParagons\CaveMonkeyParagon.cs" />
      <EmbeddedResource Include="Towers\Paragons\ModdedParagons\CyberMonkey.cs" />
      <EmbeddedResource Include="Towers\Paragons\ModdedParagons\MonkeyOfLight.cs" />
      <EmbeddedResource Include="Towers\Paragons\ModdedParagons\PlasmaMonkey.cs" />
    </ItemGroup>
</Project>
